export const StackIcons = {
  javascript: { name: "Javascript", iconSrc: "skill-icons:javascript" },
  nodejs: { name: "NodeJS", iconSrc: "logos:nodejs" },
  react: { name: "React", iconSrc: "skill-icons:react-dark" },
  redux: { name: "Redux", iconSrc: "skill-icons:redux" },
  express: { name: "Express", iconSrc: "skill-icons:expressjs-dark" },
  typescript: { name: "TypeScript", iconSrc: "skill-icons:typescript" },
  mongodb: { name: "MongoDB", iconSrc: "skill-icons:mongodb" },
  materialUI: { name: "MaterialUI", iconSrc: "skill-icons:materialui-dark" },
  html: { name: "HTML", iconSrc: "skill-icons:html" },
  css: { name: "CSS", iconSrc: "skill-icons:css" },
  python: { name: "Python", iconSrc: "skill-icons:python-dark" },
  c: { name: "C", iconSrc: "skill-icons:c" },
  cpp: { name: "C++", iconSrc: "skill-icons:cpp" },
  csharp: { name: "C#", iconSrc: "skill-icons:cs" },
  rust: { name: "Rust", iconSrc: "skill-icons:rust" },
  java: { name: "Java", iconSrc: "skill-icons:java-dark" },
  django: { name: "Django", iconSrc: "skill-icons:django" },
  selenium: { name: "Selenium", iconSrc: "skill-icons:selenium" },
  jest: { name: "Jest", iconSrc: "skill-icons:jest" },
  sql: { name: "SQL", iconSrc: "vscode-icons:file-type-sql" },
  mssql: { name: "MS SQL", iconSrc: "simple-icons:microsoftsqlserver" },
  docker: { name: "Docker", iconSrc: "skill-icons:docker" },
  gcp: { name: "Google Cloud", iconSrc: "skill-icons:gcp-dark" },
  postgresql: { name: "PostgreSQL", iconSrc: "skill-icons:postgresql-dark" },
  postman: { name: "Postman", iconSrc: "skill-icons:postman" },
  git: { name: "Git", iconSrc: "skill-icons:git" },
};
